name: just_play
description: Technical test for JustPlay

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  firebase_core: ^2.20.0
  bloc: ^8.1.2
  json_annotation: ^4.8.1
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  dart_code_metrics_presets: ^2.5.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/data/cities.json

