name: just_play
description: Technical test for JustPlay
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  reactive_forms: ^16.1.1
  reactive_forms_annotations: ^4.2.0
  reactive_forms_generator: ^4.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  dart_code_metrics_presets: ^2.5.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/data/cities.json
    - assets/images/
    - assets/images/sports/
  uses-material-design: true
